services:
  mongo:
    image: mongo:latest
    container_name: nestjs_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db  # MongoDB'nin verilerini saklamak için volume kullanıyoruz

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/nestjs-db
    volumes:
      - .:/app  # Yerel dosyalarınızı konteynere yansıtın
      - /app/node_modules  # node_modules dizini yerel sistemle eşleşir
    command: pnpm run start:dev

volumes:
  mongo-data:  # MongoDB verileri burada saklanacak